import type { StorybookConfig } from "@storybook/nextjs"
import { VanillaExtractPlugin } from "@vanilla-extract/webpack-plugin"
import MiniCssExtractPlugin from "mini-css-extract-plugin"
import merge from "webpack-merge"
import path from "path"

const config: StorybookConfig = {
    stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
    addons: [
        "@storybook/addon-onboarding",
        "@storybook/addon-links",
        "@storybook/addon-essentials",
        "@chromatic-com/storybook",
        "@storybook/addon-interactions",
        "@storybook/addon-styling-webpack",
        {
            name: "@storybook/addon-styling-webpack",
            options: {
                plugins: [
                    new VanillaExtractPlugin(),
                    new MiniCssExtractPlugin(),
                ],
                rules: [
                    {
                        test: /\.css$/,
                        sideEffects: true,
                        use: [
                            require.resolve("style-loader"),
                            {
                                loader: require.resolve("css-loader"),
                                options: {},
                            },
                        ],
                        exclude: /\.vanilla\.css$/,
                    },
                    {
                        // Targets only CSS files generated by vanilla-extract
                        test: /\.vanilla\.css$/i,
                        sideEffects: true,
                        use: [
                            MiniCssExtractPlugin.loader,
                            {
                                loader: require.resolve("css-loader"),
                                options: {
                                    // Required as image imports should be handled via JS/TS import statements
                                    url: false,
                                },
                            },
                        ],
                    },
                ],
            },
        },
    ],

    framework: {
        name: "@storybook/nextjs",
        options: {},
    },
    docs: {
        autodocs: "tag",
    },
    webpackFinal: async (config) => {
        merge(config, {
            plugins: [new VanillaExtractPlugin(), new MiniCssExtractPlugin()],
        })

        if (config.resolve) {
            config.resolve.alias = {
                ...config.resolve.alias,
                "@": path.resolve(__dirname, "../src"),
            }
        }

        merge(config, {
            plugins: [new VanillaExtractPlugin(), new MiniCssExtractPlugin()],
        })

        return config
    },

    staticDirs: ["../public"],
}
export default config
